<template>
	<main>
		<h1>This is the home page</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut dui justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce porttitor tincidunt magna, sit amet mollis tortor sollicitudin et. Donec sollicitudin in tellus vel aliquet. Nunc ornare condimentum tempus. Suspendisse suscipit nulla et blandit auctor. Aenean vestibulum lacinia ipsum, in finibus diam ultrices nec. Phasellus gravida massa urna, tempus porta leo accumsan non. Quisque molestie ac sem ac lobortis. Duis lobortis quis mauris ac placerat. Quisque ut orci felis. Maecenas egestas neque massa, sit amet ullamcorper est tincidunt sit amet. Mauris sed felis volutpat, iaculis nunc et, lobortis magna. </p>	
	</main>
</template>
<style scoped>
	main {
		padding: 0 2rem;
		width: 20%;
	}
</style>